/**
 * The bridge's hand-written engine declarations say what the engine takes.
 *
 * `ActionWiring` holds link D by asking whether a name the bridge calls EXISTS
 * on `AxiaEngine`. This file asks the next question down, which no guard in the
 * repo asked before: whether the declaration the bridge calls through says what
 * the engine actually accepts.
 *
 * It is a real gap and not a theoretical one, because of one line:
 *
 *     type AxiaEngineExtended = AxiaEngine & { ... 342 optional members ... };
 *
 * That is an INTERSECTION. Where a name appears both in the real class (from
 * `axia_wasm.d.ts`, generated by wasm-pack) and in the hand-written block,
 * TypeScript does not reconcile them — it forms an OVERLOAD SET. A call that
 * matches either signature compiles. So a hand-written declaration with the
 * wrong arity, or the right arity in the wrong order, is accepted by tsc and
 * mishandled by the engine, and nothing says so. wasm-bindgen fills a missing
 * trailing argument with 0 rather than throwing, which is the same silence the
 * `엣지 챔퍼` menu item lived in for as long as it existed.
 *
 * Measured when this landed (2026-10-01), against 344 hand-written members and
 * 414 real methods:
 *
 *     arity mismatch                    0   (7 variadic, listed below)
 *     reordered parameters              0
 *     names absent from the real class  0   (2 removed in this change:
 *                                            `drawPolyline`, retired by
 *                                            ADR-087 K-ζ, and
 *                                            `get_dirty_face_count`)
 *     agree exactly                   259
 *     differ in spelling only          75   (`edgeId` ↔ `edge_id_raw`)
 *
 * The two removed ones were landmines rather than defects: nothing called them,
 * so nothing was broken, but a call written tomorrow would have compiled and
 * no-opped forever. Deleting the declarations moves that catch from this test
 * to the compiler, which is the better place for it.
 *
 * ⚠ WHAT THIS DOES NOT CATCH, and the 75 above are why: a reorder is only
 * visible when the two sides spell the parameters the same way. `(faceId, r)`
 * against a real `(radius, face_id)` is caught — same name multiset, different
 * order. `(fid, r)` against the same real signature is not: the multisets
 * differ, so it lands in "spelling only" and is waved through. Narrowing the
 * spelling gap would make this check total; mapping 75 names by hand to get
 * there is not obviously worth it while the arity and order checks hold.
 *
 * ⚠ THE PREMISE TEST IS LOAD-BEARING, measured by breaking the `.d.ts` parser
 * the way it broke once before (a 2-space pattern on a 4-space file): the arity
 * and reorder checks both PASSED against an empty engine map, because they skip
 * any name they cannot find on the engine. What failed was `both sides were
 * parsed` and, as a second backstop, `names an export the engine does not
 * have` — every member became a phantom at once. Keep those two.
 *
 * ⚠ AND IT SAYS NOTHING ABOUT VALUES. The chamfer defect was a literal `1`
 * passed into a parameter the engine range-checks (`ensure!(segments >= 2)`),
 * and every signature in it was correct. Swept for siblings on 2026-10-01 —
 * every bridge call site in `tools/`, `ui/`, `commands/` and `main.ts` that
 * passes a bare numeric literal, against every entry guard in `axia-geo`
 * (`count >= 1`, `segments >= 2|3`, `k >= 3`, `dist > ε`) — and found none:
 * `arrayLinear*(…, 1, …)` satisfies `count >= 1`, `filletEdge(…, 8)` satisfies
 * `segments >= 2`, and `drawLineAsShape(…, 0, 0, 0)` is the engine's own
 * documented sentinel for "no normal hint" (`draw_line_as_shape` maps the zero
 * vector to `None`). Values stay measured per op, as the map header says.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const webRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const read = (p: string) => readFileSync(resolve(webRoot, p), 'utf-8');

/**
 * The 7 members declared `(...args: number[])`, which switches tsc off for
 * every call through them. Four are reached by a wrapper that spreads the real
 * argument list through `Function.prototype.call`, and those were counted by
 * hand on 2026-10-01 against the generated signature: `drawArcWithCurve` 13,
 * `setFaceSurfaceCylinder` 15, `setFaceSurfaceSphere` 9,
 * `injectExternalFacePlane` 10 — all correct. The other three have no caller at
 * all. A new name joining this list is a new hole, so it has to be added here
 * deliberately.
 */
const VARIADIC = [
  'drawArcWithCurve',
  'injectExternalFacePlane',
  'setFaceSurfaceCone',
  'setFaceSurfaceCylinder',
  'setFaceSurfacePlane',
  'setFaceSurfaceSphere',
  'setFaceSurfaceTorus',
] as const;

type Param = { name: string; type: string };

function stripComments(s: string): string {
  return s.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/[^\n]*/g, '');
}

/** Split on commas that are not nested inside brackets. */
function splitTop(s: string): string[] {
  const out: string[] = [];
  let depth = 0;
  let cur = '';
  for (const ch of s) {
    if ('([{<'.includes(ch)) depth++;
    else if (')]}>'.includes(ch)) depth--;
    if (ch === ',' && depth === 0) {
      out.push(cur);
      cur = '';
    } else cur += ch;
  }
  if (cur.trim()) out.push(cur);
  return out.map((x) => x.trim()).filter(Boolean);
}

/** `edge_id_raw: number` → `{ name: 'edgeidraw', type: 'number' }`. */
function parseParams(list: string): Param[] {
  return splitTop(list).map((x) => {
    const m = /^(\.\.\.)?([A-Za-z_$][\w$]*)\??\s*:\s*([\s\S]+)$/.exec(x);
    if (!m) return { name: '?', type: x.replace(/\s+/g, '') };
    return {
      name: m[2].replace(/_/g, '').toLowerCase(),
      type: m[3].replace(/\s+/g, ''),
    };
  });
}

/**
 * Members of a `{ … }` block, with their parameter lists. Walks braces and
 * parens rather than matching a line, because several declarations and most
 * generated signatures span lines.
 */
function members(text: string, marker: string, memberRe: RegExp): Map<string, Param[][]> {
  const at = text.indexOf(marker);
  if (at < 0) return new Map();
  const open = at + text.slice(at).indexOf('{');
  let depth = 0;
  let k = open;
  for (;;) {
    if (text[k] === '{') depth++;
    else if (text[k] === '}') {
      depth--;
      if (depth === 0) break;
    }
    k++;
  }
  const body = stripComments(text.slice(open + 1, k));

  const out = new Map<string, Param[][]>();
  for (const m of body.matchAll(memberRe)) {
    let p = (m.index ?? 0) + m[0].length;
    const from = p;
    let d = 1;
    while (d > 0) {
      if (body[p] === '(') d++;
      else if (body[p] === ')') d--;
      p++;
    }
    const sig = parseParams(body.slice(from, p - 1));
    const prev = out.get(m[1]);
    if (prev) prev.push(sig);
    else out.set(m[1], [sig]);
  }
  return out;
}

/** The real `AxiaEngine` class, generated by wasm-pack. 4-space indentation. */
function realEngine(): Map<string, Param[][]> {
  return members(
    read('src/wasm/axia_wasm.d.ts'),
    'export class AxiaEngine {',
    /(?:^|\n)[ \t]*(?:static[ \t]+)?([A-Za-z_$][\w$]*)[ \t]*\(/g,
  );
}

/** The hand-written half of `AxiaEngineExtended`. 2-space indentation. */
function handWritten(): Map<string, Param[][]> {
  return members(
    read('src/bridge/WasmBridge.ts'),
    'type AxiaEngineExtended = AxiaEngine & {',
    /(?:^|\n)[ \t]*([A-Za-z_$][\w$]*)\??[ \t]*\(/g,
  );
}

/** The names declared `(...args: …)`, read straight from the source. */
function variadicNames(): string[] {
  const src = read('src/bridge/WasmBridge.ts');
  const from = src.indexOf('type AxiaEngineExtended = AxiaEngine & {');
  const block = src.slice(from, from + src.slice(from).indexOf('\n};'));
  return [
    ...new Set(
      [...block.matchAll(/\n[ \t]*([A-Za-z_$][\w$]*)\??\(\.\.\./g)].map((m) => m[1]),
    ),
  ].sort();
}

describe('the bridge declares what the engine takes', () => {
  it('both sides were parsed', () => {
    // PREMISE. Each parser has broken silently in this repo before — the .d.ts
    // one because its indentation is 4 spaces and the pattern asked for 2, and
    // an empty extraction makes every assertion below vacuously true without
    // failing anything.
    const real = realEngine();
    const hand = handWritten();

    expect(real.size, 'the generated AxiaEngine class must be parsed').toBeGreaterThan(380);
    expect(hand.size, 'the hand-written block must be parsed').toBeGreaterThan(300);

    // Named witnesses, so a pattern that stops matching fails rather than shrinks.
    for (const w of ['create_box', 'chamferEdge', 'drawEllipseAsCurve']) {
      expect([...real.keys()], `.d.ts parser must find ${w}`).toContain(w);
    }
    for (const w of ['lastError', 'batchEraseEdgesWithMerge', 'getCacheVersion']) {
      expect([...hand.keys()], `bridge parser must find ${w}`).toContain(w);
    }

    // And that the parameter lists came with them: a member map full of empty
    // signatures would pass the counts above and check nothing afterwards.
    expect(real.get('chamferEdge')?.[0].map((p) => p.name)).toEqual(['edgeidraw', 'dist']);
    expect(real.get('create_box')?.[0]).toHaveLength(6);
    expect(hand.get('batchEraseEdgesWithMerge')?.[0]).toHaveLength(4);
  });

  it('every hand-written declaration takes as many arguments as the engine', () => {
    const real = realEngine();
    const hand = handWritten();
    const variadic = new Set<string>(VARIADIC);

    const mismatch: string[] = [];
    for (const [name, sigs] of hand) {
      if (variadic.has(name)) continue;
      const theirs = real.get(name);
      if (!theirs) continue; // the phantom test below owns that case
      const n = sigs[0].length;
      if (!theirs.some((t) => t.length === n)) {
        mismatch.push(
          `${name}: bridge declares ${n} parameter(s), engine takes ` +
            theirs.map((t) => t.length).join(' or '),
        );
      }
    }

    expect(
      mismatch,
      'the intersection type turns a wrong arity into an accepted overload: ' +
        'tsc compiles the call and wasm-bindgen fills the gap with 0.\n' +
        mismatch.join('\n'),
    ).toEqual([]);
  });

  it('no hand-written declaration reorders the engine parameters', () => {
    const real = realEngine();
    const hand = handWritten();
    const variadic = new Set<string>(VARIADIC);

    const reordered: string[] = [];
    for (const [name, sigs] of hand) {
      if (variadic.has(name)) continue;
      const mine = sigs[0];
      const theirs = (real.get(name) ?? []).find((t) => t.length === mine.length);
      if (!theirs) continue;

      const a = mine.map((p) => p.name);
      const b = theirs.map((p) => p.name);
      // Only comparable when both sides spell the parameters the same way; see
      // the header for what that leaves out.
      const sameSet = [...a].sort().join('|') === [...b].sort().join('|');
      if (sameSet && a.join('|') !== b.join('|')) {
        reordered.push(`${name}: bridge [${a}] vs engine [${b}]`);
      }
    }

    expect(
      reordered,
      'a reorder keeps the arity, so tsc accepts it and the engine reads the ' +
        'arguments in the wrong slots.\n' + reordered.join('\n'),
    ).toEqual([]);
  });

  it('no hand-written declaration names an export the engine does not have', () => {
    const real = realEngine();
    const hand = handWritten();

    // A name here is reachable through `this.engine.X?.()` with tsc's blessing
    // and no export behind it, which is a permanent silent no-op. `ActionWiring`
    // catches it once something CALLS it; this catches the declaration itself,
    // so the compiler rejects the call instead.
    const phantom = [...hand.keys()].filter((n) => !real.has(n));

    expect(
      phantom,
      'declared on AxiaEngineExtended with no export behind it. Either the ' +
        'export was retired (delete the declaration — tsc then rejects any ' +
        'call) or it was never added (add it to the engine).\n' +
        phantom.join('\n'),
    ).toEqual([]);
  });

  it('the variadic escape hatches are the ones we know about', () => {
    // PREMISE: the reader finds them at all. A pattern that stops matching
    // would leave this comparing two empty lists.
    const found = variadicNames();
    expect(found.length, 'the variadic reader must find some').toBeGreaterThan(0);

    expect(
      found,
      'a `(...args: number[])` declaration switches tsc off for every call ' +
        'through it. The four with callers were counted by hand (see the ' +
        'header); a new one needs the same treatment before it goes on this list.',
    ).toEqual([...VARIADIC].sort());
  });
});
