// ADR-043 P28 — pure scaffold logic, no I/O. Easy to test.
//
// `buildScaffold(opts)` returns a `ScaffoldFiles` map: relative path → text
// content. Caller writes them to disk.

import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { readFileSync } from 'node:fs';

/**
 * Pinned semver range for `@axia/mcp-server`. Bumped MAJOR when ADR-041
 * P26.2 schema MAJOR bumps; otherwise caret = forward-compatible.
 */
export const MCP_SERVER_VERSION_RANGE = '^0.1.0';

export interface ScaffoldOptions {
  /** Project name — written to package.json. Lowercase, npm-valid. */
  projectName: string;
  /** Initial tier configuration. Default: [0, 1] (read + constructive). */
  enabledTiers?: number[];
  /** Optional ALLOW capability list. Empty by default. */
  allowCaps?: string[];
  /** Optional DENY capability list. Empty by default. */
  denyCaps?: string[];
  /** Client identifier for audit logs. Default: 'unknown'. */
  client?: string;
  /** When true, use a relative `file:` link to a local @axia/mcp-server
   *  workspace (mode B from P28.3). Tests use this to avoid npm install
   *  hitting the network. */
  localServerPath?: string;
}

export type ScaffoldFiles = Map<string, string>;

export function buildScaffold(opts: ScaffoldOptions): ScaffoldFiles {
  const projectName = sanitizeProjectName(opts.projectName);
  const enabledTiers = opts.enabledTiers ?? [0, 1];
  const allowCaps = opts.allowCaps ?? [];
  const denyCaps = opts.denyCaps ?? [];
  const client = opts.client ?? 'unknown';

  const files: ScaffoldFiles = new Map();

  files.set('package.json', renderPackageJson(projectName, opts.localServerPath));
  files.set(
    'axia-mcp.config.json',
    renderConfigJson(enabledTiers, allowCaps, denyCaps, client),
  );
  files.set(
    'claude_desktop_config.snippet.json',
    renderClaudeDesktopSnippet(projectName),
  );
  files.set('README.md', renderReadme(projectName, enabledTiers));

  return files;
}

/**
 * Validate a user-supplied project name. ADR-043 P28.1 — must be a valid
 * npm package name (lowercase, no spaces, no leading dot/underscore).
 */
export function sanitizeProjectName(raw: string): string {
  const trimmed = raw.trim();
  if (trimmed.length === 0) {
    throw new Error('Project name must not be empty.');
  }
  if (trimmed.length > 214) {
    throw new Error('Project name must be ≤ 214 characters (npm rule).');
  }
  if (!/^[a-z0-9][a-z0-9._-]*$/.test(trimmed)) {
    throw new Error(
      `Invalid project name "${raw}" — must be lowercase, ` +
        'start with [a-z0-9], use only [a-z0-9._-].',
    );
  }
  return trimmed;
}

function renderPackageJson(projectName: string, localServerPath?: string): string {
  const serverDep = localServerPath
    ? `file:${localServerPath}`
    : MCP_SERVER_VERSION_RANGE;
  return (
    JSON.stringify(
      {
        name: projectName,
        version: '0.1.0',
        private: true,
        type: 'module',
        description: 'AxiA 3D MCP server instance — see ADR-041, ADR-042, ADR-043',
        scripts: {
          start: 'axia-mcp-server',
          'check:wasm':
            'node node_modules/@axia/mcp-server/scripts/check-wasm.mjs',
        },
        dependencies: {
          '@axia/mcp-server': serverDep,
        },
        engines: {
          node: '>=20',
        },
      },
      null,
      2,
    ) + '\n'
  );
}

function renderConfigJson(
  enabledTiers: number[],
  allowCaps: string[],
  denyCaps: string[],
  client: string,
): string {
  return (
    JSON.stringify(
      {
        $schema: 'https://axia.dev/schemas/mcp.config.v1.json',
        client,
        enabled_tiers: enabledTiers,
        allow_caps: allowCaps,
        deny_caps: denyCaps,
      },
      null,
      2,
    ) + '\n'
  );
}

function renderClaudeDesktopSnippet(projectName: string): string {
  return (
    JSON.stringify(
      {
        mcpServers: {
          [projectName]: {
            command: 'npx',
            args: ['axia-mcp-server'],
            env: {
              AXIA_MCP_TIERS: '0,1',
              AXIA_MCP_CLIENT: 'claude-desktop',
            },
          },
        },
      },
      null,
      2,
    ) + '\n'
  );
}

function renderReadme(projectName: string, enabledTiers: number[]): string {
  const tierList = enabledTiers.join(', ');
  return [
    `# ${projectName}`,
    '',
    'AxiA 3D MCP server instance. Generated by `npm create axia-mcp`.',
    '',
    '## Quickstart (5 steps)',
    '',
    '1. **Install dependencies**',
    '   ```bash',
    '   npm install',
    '   ```',
    '',
    '2. **Verify the engine WASM is available**',
    '   ```bash',
    '   npm run check:wasm',
    '   ```',
    '   If you see "WASM not built", follow the printed instructions.',
    '',
    '3. **Register with Claude Desktop**',
    '   Copy `claude_desktop_config.snippet.json` content into your Claude',
    '   Desktop config (~/Library/Application Support/Claude/ on macOS, %APPDATA%\\Claude\\ on Windows).',
    '',
    '4. **Restart Claude Desktop**',
    '',
    `5. **Try it** — ask Claude to "draw a 100mm rectangle at the origin".`,
    '',
    '## Configuration',
    '',
    `Tier defaults: \`[${tierList}]\` (0 = read, 1 = construct, 2 = modify, 3 = destroy).`,
    '',
    'Override at runtime via env:',
    '```bash',
    'AXIA_MCP_TIERS=0,1,2 npm start                # enable Tier 2',
    'AXIA_MCP_DENY_CAPS=boolean_subtract npm start # selective denial',
    'AXIA_MCP_ALLOW_CAPS=push_pull npm start       # additive allow',
    '```',
    '',
    'See `axia-mcp.config.json` for the persistent config (currently advisory —',
    'env vars take precedence; future PR will read this file directly).',
    '',
    '## ADR references',
    '',
    '- ADR-041 — Capability Surface (4-tier whitelist)',
    '- ADR-042 — ALLOW/DENY policy (additive composition)',
    '- ADR-043 — This scaffold (npm create axia-mcp)',
    '',
  ].join('\n');
}

/**
 * Resolve the bundled template directory (when this file is shipped via
 * an npm install). Templates are NOT used directly — kept for future
 * static asset support. P28.1 says scaffold 자체는 capability 미복제.
 */
export function templateDir(): string {
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = dirname(__filename);
  return resolve(__dirname, '../template');
}

/** Read a static template asset (future use). */
export function readTemplateAsset(relativePath: string): string {
  return readFileSync(resolve(templateDir(), relativePath), 'utf8');
}
